"""
Tratamento de erros
"""

try:
    geek() #funcao que nao existe
except:
    print("Erro12313")